package com.suleiman.techkriti.model;

/**
 * Created by HP on 05-Jan-16.
 */
public class entreprenuerial {
    public String name;

    public static final String[] data = {"Home", "challenge Areas", "eventstructure","Rules","contacts","FAQs"};
    entreprenuerial(String name){this.name=name;}

    public static class tab1{
        public String name;
        public static final String data1="\"Information is the oil of 21st century, and analytics is the combustion engine.\"<br><br>The field of analytics is ever changing and today it forms the crux of all strategic decisions taken in the business world. With the innovation and cutting edge technology at our disposal today, it is possible to analyse tons of data like never before. With that in mind Buizkriti\'16 brings to you \'Battlefield\'-the ultimate analytics battleground where the main focus is on data analysis i.e. revealing hidden patterns and co-relations";
        public static final String data2="\"Marketing is no longer about the stuff you make but about the stories you tell\".<br><br>The concept of marketing has evolved over the years to encompass everything from idea conceptualization to the final sale. To be a smart marketeer you need to understand customer needs better than your competitor does. <br>\"Marketing Villa\" is back at buizkriti to bring out the smartest and most innovative marketing concepts from all over the country. So get ready and join us in marketing villa!";
        public static final String data3="\"Execution is the ability to mesh strategy and reality, align people with goals and achieve the promised results.\" <br>Be the Tycoon is a business simulation game created to test your competitive skills in the real world situations using strategy and innovation as your tools. Analytics, evaluation and synthesis in cost management and predicting the outcome of the chosen strategy based on the action of your competitors are the focal points of the game. The game requires a crucial mix of theoretical knowledge and practical hands on decision making to give you a managerial feel.";
        public static final String data4="\"Logic will get you from A to B, but imagination will take you everywhere.\" <br><br>To bring you closer to us, Techkriti\'16 brings you a set of interesting online events to check your knowledge and creativity, give you a learning experience and at the same time for you to have some fun. With prizes worth ....... waiting to be won, the opportunity is here for you to grab. So open your systems and hook up your internet, there\'s an online war brewing up.";
        public static final String data5="\"The most important organ in the body as far as the stock market is concerned is the guts, not the head\".<br><br>The biggest fantasy stock market is back at Techkriti\'16. Stocksim is the real time simulation of stock market where you get the chance to experience thrills and frills of the dalal street. The virtual market price of shares is kept updated in real time with BSE and NSE. If you think you are ready to ride the bull, come join this world of thrills and chills, soaring joy and crashing heartbreak at Techkriti\'16.";
        public static final String data6="\"No great manager or leader ever fell from the heaven, its learned not inherited\"<br><br>It will consist of a string of various interesting competitions to test the innovation, managerial skills, communication skills and knowledge of the participants. Best Manager gives you an opportunity to sharpen the managerial skills in you and also to be declared the best amongst the lot.";
        public static final String data7="The Business Venture event provides the platform where your start-up can find its foundation. Apart from the capital, you can attract the attention and advice of the panel and not to forget the immense networking, informal interaction and feedback from the judges. This contest aims at laying a carpet on your rugged road to establishing a big company, by providing proper mentorship and guidance. Our vast network of venture capitalists, angel investors, incubation hubs and entrepreneurs who serve as mentors and incubators makes sure you get connected to the right people in the industry. Certainly not an opportunity to be missed!";
        public static final String data8="It is a platform to showcase any new venture that has a central focus on addressing challenges faced by the society and on creating social values. In this contest entries may include non-profit, for-profit, or hybrid model business plans.";
        public static final String data9= "Have a start-up idea?? Elevator Pitch provides you the opportunity to present your start up idea in front of masterminds of the field. The emphasis of Elevator Pitch of Ideas is to nurture leaders who dare to unravel the dynamic world of business with their creativity, imaginative thinking and entrepreneurship skills.";
        public static final String data10="This competition organized by Biological Sciences &amp; Bioengineering Department of </th><b>IIT Kanpur</b> under the auspices of the Joy and Manmohan Gill Endowment Fund is designed to inculcate the research in the field of bioengineering to ignite the flames of entrepreneurship among graduate &amp; undergraduate students throughout the country.<br><br>The event aims to provide the right platform for budding bio-entrepreneurs to act on their ideas and talents to come up with a model that combines business and biology which is both innovative and viable.";
        public static final String data11="Internet of things is a competition that provides a platform for the startups that are working in the field of Internet of Things to get their foundation. Again, in this contest, teams will get an opportunity to get mentorship and guidance from VC\'s and venture partners in addition to various other incentives.";
    }
    public static class tab2{
        public String name;
        public static final String data1="Round-1:  <br>It will be an Off-Campus round where participants will be given a case study based on Data Analytics and they will need to submit their analysis before the deadline. <br>Round-2:  <br>It will be an On-campus round where participants need to present their case.";
        public static final String data2="Round-1:  <br>Registration will start from 10th January  It will be an Ad making round. Participants will be asked to prepare a video of 120 seconds (max limit) on a given theme (for which they will be notified later). The video needs to be uploaded on YouTube and the link should be mailed to the organizers by the given deadline. This video will be then shared on the Facebook page of Buizkriti (on a pre-mentioned date). The participants then can start promoting their videos through Facebook page of Buizkriti. <br>This will be an elimination round. All eligible videos will be scored by a Judging panel on the basis of judging criteria (as mentioned). <br>Round-2:  It will be a Product based marketing round. The details of which will be notified to the registered teams.";
        public static final String data3="Round-1: <br>Number of questions: 35-50 (will be notified later) <br>It will be an online quiz to test the knowledge of the participants regarding general business awareness. <br>Duration of quiz: 30 minutes <br><br>Round-2: <br>It will be a Business simulation game round. The details of which will be notified to the registered participants.";
        public static final String data4="</th><b>Finatics (Online Finance Quiz)</b> :This will be hosted on dare2compete.com . It will have 30multiple-choice questions related to different streams of Finance. Time window for the eventwill be of 20 minutes and the results will be declared the next day.<br></b><b>Mark-Ops (online Marketing and Operation Quiz)</b> : It will be held in two parts:Part 1  - It will have 50 multiple choice questions related to different streams of marketing.Time window for the event will be 30 minutes.Part 2  - It will have 30 multiple choice questions based on the field of operations. Timewindow for the event will be 20 minutes.";
        public static final String data5="Stocksim will be held in two independent rounds. <br>Round 1  - Bull Run <br>No rider has ever tamed the Wall Street bull on the first go. So tighten your saddle and get your grip on the game with the preliminary round! <br>1. Trading starts from Jan - 20, 2016 to Jan - 24, 2016 <br>2. Top 5 rankers get 10 point bonus for round 2 <br>Round 2  - Final Destination <br>Date of competition : Feb-24, 2016 to Mar-4, 2016";
        public static final String data6="There will be three rounds.<br><br>Round 1: Pen and Paper Round<br><br>In this round, a questionnaire will be given that will include personal questions and trivia as well.<br><br>Round 2: Task Round<br><br>A task will be given to be performed within the grounds of the campus. It will test the time management and communicative skills.<br><br>Round 3: Market your product<br><br>Each participant will be allotted a hypothetical product about which they will perform various tasks. This round will test the marketing and managerial skills of participants.";
        public static final String data7="</th><b>Round I</b><br>Submission of Executive summary or Pitch Deck<br><br></b><b>Round II</b><br>Mentorship Program: A \'14 days long\' intensive program where each team gets mentored by experienced entrepreneurs and venture partners<br></b><b>Round III(Pre-Final)</b><br>Elevator Pitching (it will be graded for Round III and will also be considered as an entry to the competition \'Elevator Pitch\')<br></b><b>Round IV(Final)</b><br>Closed door pitching in front of the reputed VC's of India; 10-min presentation followed by Q&amp;As.<br><br></b><b>Note:</b> The Pre-Final and Final Rounds will take place here at Techkriti and teams should come down to IIT Kanpur for the same during 3rd to 6th March \'16.";
        public static final String data8="The Social Track event aims at helping build innovative enterprises and technology to aid the strata at the bottom of the pyramid and build a sustainable future. It is a platform to showcase any new venture that has a central focus on addressing challenges faced by the society and on creating social values. Social Venture Contest entries may include non-profit, for-profit, or hybrid model business plans";
        public static final String data9= "1)A short summary to quickly and simply define your idea, product or service and its value proposition in about 90 seconds.<br>2)This competition doesn\'t require any pre-registration. Participants can simply walk in at the time of the event.<br>3)Date: 3rd-6th March'16";
        public static final String data10="</b><b>Round-1</b><br></b><div>Teams would be selected on the basis of abstract submissions.</div></div><b>Round-2</b><br></b><div>There would be a 10-minute Pitch and Presentation round followed by Q&amp;As in front of the judging panel.</div>";
        public static final String data11="Internet of Things is a competition where participants get a platform to present their business plans related to internet of things. Here start-ups get guidance from India's finest mentors and also an opportunity for networking, team creation and to raise seed funding.";

    }
    public static class tab3{
        public String name;
        public static final String data1="1. Register with a valid Techkriti ID. 2. A team member cannot register in more than one team. <br>3. Each Team will have 2-3 participants.<br>4. Any number of teams can participate from a college. <br>5. The event consists of 2 rounds(Round 1- Online , Round 2- On Campus). <br>6. Teams qualifying in first round will proceed to the next round. <br>7. Only college students will be considered while deciding winners. <br>8. The decision of the Judges is final and incontestable. <br>9. Organizers reserve the right to change the Timelines.";
        public static final String data2="1. Register with a valid Techkriti ID.<br>2. A team member cannot register in more than one team. <br>3. Each Team will have 2-3 participants. <br>4. Any number of teams can participate from a college. <br>5. The event consists of 2 rounds(Round 1- Online , Round 2- On Campus). <br>6. Only the top 10 winners of the first round will proceed to the next round.<br>7. Only college students will be considered while deciding winners <br>8. The decision of the Judges is final and incontestable. <br>9. Organizers reserve the right to change the Timelines <br>The following will lead to disqualification, if the video:  <br>a. Has plagiarised content. <br>b. Has controversial, vulgar or offensive content. <br>c. Does not adhere to deadline for submission.   ";
        public static final String data3="1. Register with a valid Techkriti ID.<br>2. This is an individual event and a student can register only once. <br>3. The event consists of 2 rounds(Round 1- Online , Round 2- on campus).<br>4. The rules and decisions of the judging panel and organizing team in all matters related to the event are final.<br>5. The judging panel and organizing team reserve the right, in their sole discretion, to disqualify any individual they find or believe that participant has tampered with the process (in any form) of the competition, or violated the rules and guidelines.  <br>6. Organizers reserve the right to change the Timelines.";
        public static final String data4="1. Register with a valid Techkriti ID <br>2. Only college students will be considered while deciding winners <br>3. Organizers reserve the right to change the Timelines <br>4. For Finatics, each team will have 2-3 participants. <br>5. No team member can register in more than one team.";
        public static final String data5="<br><br> <br><b>Meenal Gupta:  </b>9452482497</b><br><b>Somya Goel:  </b>9453148468</b><br><b>Bhavna Uttamchandani:  </b>9453994844</b> <br><b>Gaurav Dawrani:  </b>9049917788</b><br><b>Sofia Sunny Thomas:  </b>9645541911<br></b>";
        public static final String data6="* Register with a valid Techkriti ID.<br><br>* The event consists f 3 rounds (On Campus).<br><br>* Each round will be an elimination round.<br><br>* The decision of the Judges is final and incontestable.<br><br>* Organizers reserve the right to change the Timelines.";
        public static final String data7="The round I requires an Executive Summary of Business Plan or a Pitch Deck to be submitted in the format described as under.<br><br></b><b>Deadline for First Round Entries:</b> \\u00a011:59 pm, 15th January, 2015<br><br></b><b>Downloads:-</b><br></b><a href=\"http://m.techkriti.org/%22http:////2012.techkriti.org//assets//Competitions//Executive-Summary.docx/%22\">Executive Summary Form</a><br></a><a href=\"http://m.techkriti.org/%22http:////2012.techkriti.org//assets//Competitions//Executive-Summary-Example.pdf/%22\">Executive Summary Example</a><br></a><a href=\"http://m.techkriti.org/%22#\\&quot;\">Pitch Deck Form</a><br></a><a href=\"http://m.techkriti.org/%22#\\&quot;\">Pitch Deck Example</a><br></a><a href=\"http://m.techkriti.org/%22http:////2012.techkriti.org//assets//Competitions//Guidelines-Document.docx/%22\">Guidelines</a><br><br>1. All participants are required to fill either one of the\\u00a0Executive Summary Form\\u00a0or Pitch Deck.<br>2. The\\u00a0Executive Summary\\u00a0or Pitch Deck should adhere to the format given and own versions should not be created. Participants\\u00a0not adhering\\u00a0to the format will be disqualified.<br>3. Please study the\\u00a0Example Executive Summary\\u00a0or Pitch Deck to get an idea of the information that the teams are required to pen down on the form.<br>4. Your submission should be\\u00a0accompanied by CV\'s\\u00a0of all the members of the team.<br>5. All the documents should be\\u00a0converted to PDF\\u00a0and then mailed to\\u00a0ideas@techkriti.org.<br>6. Contestants not adhering to the rules will undergo disqualification.";
        public static final String data8="Round I<br>Submission of Executive summary<br><br>Round II<br>Mentorship Program: A \'14 days long\' intensive program where each team gets mentored by VC\'s and venture partners<br>Round III<br><br>Pre-final Round Screening <br>Date of Event : 3rd-6th March 2016<br>(Teams which didn\'t go through Round II have also been considered for this Screening)<br>A 4-min Pitching with short and detailed Presentation<br>This shall be a qualifier for the top 40 teams, which includes teams which may not have gone through the Mentorship phase (Round II) as well. This Pre-Final Round will take place here at Techkriti and Teams should come down to IIT Kanpur for the same.<br><br>Final Round<br>Date of Event : 3rd-6th March 2016<br>Closed door pitching in front of the reputed VC's of India; 10-min presentation followed by Q&amp;As.<br>Note:'Elevator Pitch' will be held as a separate open competition after the finals of the all other e-factor events and teams may choose to take part in it as well.";
        public static final String data9= "It is an open competition and hence all the participants in Techkriti'16 can come and pitch their ideas, no separate registrations are required.";
        public static final String data10="An Executive Summary of the business plan has to be submitted in the format which can be downloaded by clicking </div><a href=\"http://m.techkriti.org/%22https:////drive.google.com//file//d//0B1TtIfXSffk9Y3BJWXNKZkFmdTQ//view?usp=sharing\\%22\">here</a>. Send the filled abstract to ideas@techkriti.org";
        public static final String data11="The event would be composed of 4 rounds. <br>1)In the first round, teams have to submit an executive summary of their ideas. <br>2)The second round would be mentorship program where each team will be mentored by VC's and venture partners.<br>3)The third round would be a pitching round with a small presentation which will be held during Techkriti. <br>4)The fourth and final round would be a close door pitching in front of reputed VC's of India with a slightly detailed presentation followed by Q&amp;A(s).";
    }
    public static class tab4{
        public String name;
        public static final String data1="<br>  <br>    <br>    <br>    <br>    <br>    <br>    <br>    <table style=\"\\&quot;width:70%\\&quot;\"><tbody><tr><td>Registration Starts</td><br>    </td><td>Started</td> <br>  </tr><br>  </td></tr><tr><td>Registration Closes</td><br>    </td><td>19th Jan</td> <br>  </tr><br>  </td></tr><tr><td>Round 1(Releasing case study)</td><br>    </td><td>20th Jan</td> <br>  </tr><br>  </td></tr><tr><td>Round 1 (Deadline for Submission)</td><br>    </td><td>28th Jan</td> <br>  </tr><br>  </td></tr><tr><td>Round 1(Results)</td><br>    </td><td>4th Feb</td> <br>  </tr><br></td></tr><tr><td>Fee Payment last date</td><br>    </td><td>9th Feb</td> <br>  </tr><br></td></tr><tr><td>Final Round</td><br>    </td><td>3rd March</td> <br>  </tr><br>  <br></table>";
        public static final String data2="It is for Round 1 <br>Following Parameters will be taken into consideration in the given ratio: <br>1. 70% - o Story\\/Script o Creativity o Originality o Coherence <br>2. 30% - o Number of video likes on FB page of Buizkriti";
        public static final String data3="IMPORTANT DATES: <br></th><br>  <br>    <br>    <br>    <br>    <br>    <br>    <table style=\"\\&quot;width:70%\\&quot;\"></table><tbody><tr></tr><td>Registration Starts</td><br>    </td><td>Started</td> <br>  </tr><br>    </td></tbody><tr></tr><td>Registration Closes</td><br>    </td><td>29th Jan </td> <br>  </tr><br></td><tr></tr><td>Round 1(Quiz)</td><br>    </td><td>30th Jan</td> <br>  </tr><br></td><tr></tr><td>Round 1(Results)</td><br>    </td><td>4th Feb</td> <br>  </tr><br></td><tr></tr><td>Fee payment last date</td><br>    </td><td>8th Feb</td> <br>  </tr><br></td><tr></tr><td>Final Round (Business Simulation Game)</td><br>    </td><td>3rd March</td> <br>  </tr><br><br><br></table>";
        public static final String data4="Work  Date  <br></b><br>  <br>    <br>    <br>    <br>    <br>    <table style=\"\\&quot;width:70%\\&quot;\"></table><tbody><tr></tr><td>Registration Starts</td><br>    </td><td>Started</td> <br>  </tr><br>    </td></tbody><tr></tr><td>Registration Closes</td><br>    </td><td>3rd Feb</td> <br>  </tr><br>  </td><tr></tr><td>Finatics Quiz</td><br>    </td><td>6th Feb</td> <br>  </tr><br>  </td><tr></tr><td>Mark-Ops</td><br>    </td><td>7th Feb</td> <br>  </tr><br></td><tr></tr><td>Results</td><br>    </td><td>9th Feb</td> <br>  </tr><br></table>";
        public static final String data5="Round 1 :-<br>11th-15th Jan'16";
        public static final String data6="Work                   <br></th><br>  <br>    <br>    <br>    <table style=\"\\&quot;width:70%\\&quot;\"></table><tbody><tr></tr><td>Registration Starts</td><br>    </td><td>Started</td> <br>  </tr><br></td></tbody><tr></tr><td>Registration Closes</td><br>    </td><td>10th Jan</td> <br>  </tr><br></td><tr></tr><td>Final Round</td><br>    </td><td> 3rd March</td> <br>  </tr><br></table><br>";
        public static final String data7="➤ Students (undergraduates and graduates) and professionals across the world are eligible to participate.\\n➤ Individual participation is allowed however team participation is encouraged.\\n➤ Entries must be the original work of participants i.e. team members competing must be the principle owners of the venture.";
        public static final String data8="An Executive Summary of Business Plan has to be submitted in the format which can be downloaded by clicking </th><a href=\"http://m.techkriti.org/%22https:////drive.google.com//file//d//0B1TtIfXSffk9Y3BJWXNKZkFmdTQ//view?usp=sharing\\%22\">here</a>. The filled abstract has to be submitted by sending it to ideas@techkriti.org";
        public static final String data9= "<br><br> <br><b>Shubham Gour:  </b>9454798466<br></b><b>Manpreet Singh:  </b>9569381553<br></b><b>Deepti Sekhri:  </b>9454022488<br></b>";
        public static final String data10="▸ Students (undergraduates and graduates) and professionals across the world are eligible to participate. <br>▸ Individual participation is allowed, however team participation is encouraged.<br>▸ Entries must be the original work of participants i.e. team members competing must be the principle owners of the venture.";
        public static final String data11="1)Students (undergraduates and graduates) and professionals across the world are eligible to participate. <br>2)Individual participation is allowed, however team participation is encouraged. 3)Entries must be the original work of participants i.e. team members competing must be the principle owners of the venture.";
    }
    public static class tab5{
        public String name;
        public static final String data1="<br><br><br> <br><br><b>SOMYA GOEL:  </b>9453148468<br></b><b>BHAVNA UTTAMCHANDANI:  </b>9453994844<br><br><br></b>";
        public static final String data2="Work  Date  <br></th><br>  <br>    <br>    <br>    <br>    <br>    <br>    <br>    <br>    <br>    <br>    <br>    <table style=\"\\&quot;width:70%\\&quot;\"></table><tbody><tr></tr><td>Registration Starts</td><br>    </td><td>Started</td> <br>  </tr><br> </td></tbody><tr></tr><td>Registration Closes</td><br>    </td><td>17th Jan</td> <br>  </tr><br> </td><tr></tr><td>Theme release for video making(off campus)</td><br>    </td><td>18th Jan</td> <br>  </tr><br> </td><tr></tr><td>Last Date for submission of Video</td><br>    </td><td>28th Jan</td> <br>  </tr><br></td><tr></tr><td>Video to be Uploaded on Buizkriti Page(by participants)</td><br>    </td><td>29th Jan</td> <br>  </tr><br></td><tr></tr><td>Start Date for Promoting video</td><br>    </td><td>30th Jan</td> <br>  </tr><br></td><tr></tr><td>End date For Promoting Video</td><br>    </td><td>5th Feb</td> <br>  </tr><br></td><tr></tr><td>Round1 (Results)</td><br>    </td><td>6th Feb</td> <br>  </tr><br></td><tr></tr><td>Releasing theme details for Round 2(On Campus)</td><br>    </td><td>8th Feb</td> <br>  </tr><br></td><tr></tr><td>Fee payment last date</td><br>    </td><td>12th Feb</td> <br>  </tr><br></td><tr></tr><td>Round 2(On Campus)</td><br>    </td><td>4th Feb</td> <br>  </tr><br></table>";
        public static final String data3="<br><br> <br> <br> <b>SOMYA GOEL:  </b>9453148468 <br></b><b>GAURAV DAWRANI:  </b>9049917788 <br><br></b>";
        public static final String data4="<br><br> <br><b>MEENAL GUPTA:  </b>9452482497<br><br><br></b><b>SOFIA SUNNY THOMAS:  </b>9645541911<br><br></b>";
        public static final String data6="<br><br> <br> <br><br><b>BHAVNA UTTAMCHANDANI:  </b>9453994844<br><br></b><b>SOFIA SUNNY THOMAS:  </b>9645541911<br><br></b>";
        public static final String data7="➤ It is mandatory for participants to register online.<br><br>➤ NO offline submissions of the B-Plan for entrepreneurial events will be accepted.<br><br>➤ All the necessary documents should compulsorily be submitted along with the Executive Summary or Pitch Deck.<br><br>➤ Contestants registering for Business Venture cannot participate in Social Track, IOT and Manmohan Gill Bio Business but are allowed to participate in Elevator pitch.<br><br>➤ One participating team can submit more than one Business Plans. However, the team will have to register separately for each B-Plan it submits.<br><br>➤ Entries submitted after the deadline shall not be considered.<br><br>➤ The resources and example executive summary and pitch deck provided are only for reference.<br><br>➤ Entries need to have an innovative value (an innovative idea provides a solution for a new need, or advancement compared to existing products, services or technologies).<br><br>➤ The confidentiality of the entries\\/ ideas is guaranteed.<br><br>➤ The registration form and entries of the teams shall not be returned and their personal data will remain available only for statistical purposes.<br><br>➤ Entries remain the property of their legal owner.<br><br>➤ The mentorship program after first evaluation is expected to be 14 days long in general but may be shorter or longer.<br><br>➤ All conflicts are subject to jurisdiction of Kanpur courts only.";
        public static final String data8="1)Students (undergraduates and graduates) and professionals across the world are eligible to participate. <br>2)Individual participation is allowed, however team participation is encouraged. 3)Entries must be the original work of participants i.e. team members competing must be the principle owners of the venture.";
        public static final String data10="<br><br> <br><b>Shubham Gour:  </b>9454798466<br></b><b>Manpreet Singh:  </b>9569381553<br></b><b>Deepti Sekhri:  </b>9454022488<br></b>";
        public static final String data11="1)It is mandatory for participants to register online. <br>2)NO offline submissions of the B-Plan  will be accepted. <br>3)All the necessary documents should compulsorily be submitted along with the Executive Summary. <br>4)Contestants are free to participate in other business plan competitions as well. <br>5)One participating team can submit more than one Business Plans. However, the team will have to register separately for each B-Plan it submits. 6)Entries submitted after the deadline shall not be considered. <br>7)The resources and example executive summary provided are only for reference. Entries need to have an innovative value (an innovative idea provides a solution for a new need, or advancement compared to existing products, services or technologies). 8)The confidentiality of the entries\\/ ideas is guaranteed. <br>9)The registration form and entries of the teams shall not be returned and their personal data will remain available only for statistical purposes. <br>10)Entries remain the property of their legal owner. <br>11)The mentorship program after first evaluation is expected to be 14 days long in general but may be shorter. 12)All conflicts are subject to jurisdiction of Kanpur courts only.";
    }
    public static class tab6{
        public String name;
        public static final String data2="<br><br> <br><b>Meenal Gupta:  </b>9452482497<br><br><br></b><b>Gaurav Dawrani:  </b>9049917788<br><br></b>";
        public static final String data7="</a><b>Concept</b><br>➤ Originality of Idea<br>➤ Feasibility of the business model given the market opportunity and the venture.<br>➤Scalability, in terms of the potential for growth and replication of the venture.<br>➤ Well-conceived implementation plan and timetable.<br>➤ Overall likelihood of achieving demonstrable results.<br><br></b><b>Market</b><br>➤ Evidence of demand for the venture in the marketplace; market size and growth opportunity.<br>➤ Demonstrated knowledge of target market<br>➤ Competitive analysis , SWOT analysis<br>Marketing Plan addresses (wherever applicable): positioning, pricing, advertising, promotion, packaging, timetable.<br><br></b><b>Performance Benchmarks</b><br>➤ Outline the development of systems to track, monitor and assess the performance milestones articulated in venture plan<br><br></b><b>Financial Aspects</b><br>➤ Fundability: The potential for the venture to receive financial support from additional investors\\/donors(including opportunities for funding from foundations, social venture funds, angel investors and venture capitalists)<br>➤ The rigor and feasibility of the venture's financial model and goals<br>➤ Potential for follow-on funding to grow the venture through self-sufficiency or profitability.<br><br></b><b>Risk Assessment and Contingency Plans</b><br>➤ Identify risk factors associated with the enterprise and external environment. Develop a plan for mitigating them.<br><br></b><b>Demonstrated Leadership Ability</b><br>➤Quantify venture leader's ability to develop people, promote change and achieve results.";
        public static final String data8="1)It is mandatory for participants to register online. <br>2)NO offline submissions of the B-Plan for IDEAS\'15 will be accepted. <br>3)All the necessary documents should compulsorily be submitted along with the Executive Summary. <br>4)Contestants are free to participate in other business plan competitions as well. <br>5)One participating team can submit more than one Business Plans. However, the team will have to register separately for each B-Plan it submits. <br>6)Entries submitted after the deadline shall not be considered. <br>7)The resources and example executive summary provided are only for reference. Entries need to have an innovative value (an innovative idea provides a solution for a new need, or advancement compared to existing products, services or technologies). 8)The confidentiality of the entries ideas is guaranteed. <br>9)The registration form and entries of the teams shall not be returned and their personal data will remain available only for statistical purposes. <br>10)Entries remain the property of their legal owner. <br>11)The mentorship program after first evaluation is expected to be 14 days long in general but may be shorter. 12)All conflicts are subject to jurisdiction of Kanpur courts only.";
        public static final String data11="Concept  <br>1)Originality of Idea <br>2)Feasibility of the business model given the market opportunity and the venture. <br>3)Scalability, in terms of the potential for growth and replication of the venture. <br>4)Well-conceived implementation plan and timetable. <br>5)Overall likelihood of achieving demonstrable results.<br>  Market  <br>1)Evidence of demand for the venture in the marketplace; market size and growth opportunity. <br>2)Demonstrated knowledge of target market <br>3)Competitive analysis , SWOT analysis Marketing Plan addresses (wherever applicable): positioning, pricing, advertising, promotion, packaging, timetable.  <br><br>Performance Benchmarks  <br>1)Outline the development of systems to track, monitor and assess the performance milestones articulated in venture plan  <br><br>Financial Aspects  <br>1)Fundability: The potential for the venture to receive financial support from additional investors\\/donors(including opportunities for funding from foundations, social venture funds, angel investors and venture capitalists) <br>2)The rigor and feasibility of the venture's financial model and goals 3)Potential for follow-on funding to grow the venture through self-sufficiency or profitability.  <br><br>Risk Assessment and Contingency Plans  1)Identify risk factors associated with the enterprise and external environment. Develop a plan for mitigating them.  <br><br>Demonstrated Leadership Ability  1)Quantify venture leader's ability to develop people, promote change and achieve results.";
    }
    public static class tab7{
        public String name;
        public static final String data7="</b><br><br> <br><b>Shubham Gour:  </b>9454798466<br></b><b>Manpreet Singh:  </b>9569381553<br></b><b>Deepti Sekhri:  </b>9454022488<br></b>";
        public static final String data8="Concept  <br>1)Originality of Idea <br>2)Feasibility of the business model given the market opportunity and the venture. <br>3)Scalability, in terms of the potential for growth and replication of the venture. <br>4)Well-conceived implementation plan and timetable. <br>5)Overall likelihood of achieving demonstrable results.  <br><br>Market  <br>1)Evidence of demand for the venture in the marketplace; market size and growth opportunity. <br>2)Demonstrated knowledge of target market <br>n3)Competitive analysis , SWOT analysis Marketing Plan addresses (wherever applicable): positioning, pricing, advertising, promotion, packaging, timetable.  <br><br>Performance Benchmarks  <br>1)Outline the development of systems to track, monitor and assess the performance milestones articulated in venture plan  <br><br>Financial Aspects  <br>1)Fundability: The potential for the venture to receive financial support from additional investors\\/donors(including opportunities for funding from foundations, social venture funds, angel investors and venture capitalists) <br>2)The rigor and feasibility of the venture's financial model and goals 3)Potential for follow-on funding to grow the venture through self-sufficiency or profitability.  Risk <br><br>Assessment and Contingency Plans  1)Identify risk factors associated with the enterprise and external environment. Develop a plan for mitigating them.  <br><br>Demonstrated Leadership Ability  1)Quantify venture leader's ability to develop people, promote change and achieve results.";
        public static final String data11="To download the abstract, click </th><a href=\"http://m.techkriti.org/%22https:////drive.google.com//file//d//0B1TtIfXSffk9Y3BJWXNKZkFmdTQ//view?usp=sharing\\%22\">here</a>. Send the filled abstract to ideas@techkriti.org";
    }
    public static class tab8{
        public String name;
        public static final String data8="<br><br> <br><b>Shubham Gour:  </b>9454798466<br></b><b>Manpreet Singh:  </b>9569381553<br></b><b>Deepti Sekhri:  </b>9454022488<br></b>";
        public static final String data11="<br><br> <br><b>Shubham Gour:  </b>9454798466<br></b><b>Manpreet Singh:  </b>9569381553<br></b><b>Deepti Sekhri:  </b>9454022488<br></b>";
    }
}
